export let easy = [
  "anode", "apple", "book", "cat", "dog", "elephant", "fish", "grape", "hat", "ice", "joke",
  "kite", "lamp", "moon", "nest", "orange", "pear", "queen", "river", "sun", "tree",
  "umbrella", "vase", "wolf", "xylophone", "yarn", "zebra", "broom", "cloud", "dew",
  "egg", "fan", "glove", "horse", "iron", "jelly", "key", "lion", "map", "nut", "owl",
  "plum", "quiz", "rose", "star", "tiger", "urn", "violin", "wax", "yak", "zip", "ball",
  "chair", "door", "ear", "frog", "guitar", "hammer", "igloo", "jug", "kangaroo", "leaf",
  "able", "about", "above", "act", "add", "after", "again", "age", "ago",
  "air", "all", "also", "am", "among", "an", "and", "any", "are", "as",
  "ask", "at", "back", "bad", "be", "been", "big", "but", "by", "call",
  "can", "car", "care", "case", "cat", "cause", "child", "city", "clear", "close",
  "cold", "come", "could", "cut", "day", "did", "do", "does", "done", "down",
  "each", "early", "earth", "east", "easy", "eat", "end", "even", "ever", "eye",
  "face", "fact", "fall", "far", "feel", "few", "find", "fine", "fire", "first",
  "five", "for", "form", "found", "four", "from", "full", "get", "give", "go",
  "good", "got", "great", "had", "hand", "has", "have", "he", "head", "hear",
  "heat", "help", "her", "here", "high", "him", "his", "home", "hot", "hour",
  "how", "I", "idea", "if", "in", "into", "is", "it", "its", "just",
  "bounce", "brush", "bury", "carry", "cheer", "clap", "compete", "confuse",
  "copy", "crawl", "decide", "delay", "deliver", "deny", "destroy", "develop",
  "divide", "doubt", "drag", "drip", "employ", "encourage", "enjoy", "expand",
  "keep", "kind", "know", "land", "large", "last", "late", "lead", "learn", "leave",
  "left", "less", "let", "life", "light", "like", "line", "list", "little", "live",
  "long", "look", "love", "made", "make", "man", "many", "may", "me", "mean",
  "men", "might", "mile", "miss", "more", "most", "move", "much", "must", "my",
  "name", "near", "need", "never", "new", "next", "night", "no", "not", "now",
  "of", "off", "often", "old", "on", "once", "one", "only", "or", "other",
  "our", "out", "over", "own", "page", "part", "pay", "per", "play", "point",
  "put", "quick", "read", "real", "right", "run", "said", "same", "saw", "say",
  "school", "sea", "see", "seem", "self", "set", "she", "should", "show", "side",
  "since", "six", "small", "so", "some", "soon", "sound", "still", "such", "take",
  "tell", "ten", "than", "that", "the", "their", "them", "then", "there", " these",
  "they", "think", "this", "three", "time", "to", "too", "took", "true", "try",
  "turn", "two", "under", "up", "us", "use", "very", "want", "was", "water",
  "way", "we", "week", "well", "went", "were", "what", "when", "where", "which",
  "while", "white", "who", "why", "will", "with", "word", "work", "world", "would",
  "write", "year", "you", "young", "your", "able", "acid", "ago", "agree", "ahead",
  "air", "allow", "alone", "along", "also", "among", "anger", "angle", "angry", "animal",
  "answer", "any", "apple", "arm", "army", "around", "arrive", "art", "ask", "at",
  "atom", "away", "baby", "back", "bad", "bag", "ball", "band", "bank", "bar",
  "base", "bath", "be", "bean", "bear", "beat", "bed", "bell", "bend", "bent",
  "best", "bet", "better", "between", "beyond", "big", "bill", "bind", "bird",
  "birth", "bit", "bite", "black", "blade", "bleed", "blend", "bless", "blind",
  "block", "blood", "blow", "blue", "board", "boat", "body", "bolt", "bomb",
  "bone", "book", "boot", "born", "both", "bottle", "bottom", "bound", "bow",
  "box", "boy", "brain", "brake", "branch", "brand", "bread", "break", "breath",
  "breeze", "brick", "bridge", "brief", "bright", "bring", "broad", "broke",
  "brown", "brush", "buck", "bud", "bug", "build", "bulk", "bull", "bump",
  "burn", "burst", "bus", "busy", "but", "buy", "by",
  "cage", "cake", "call", "camp", "card", "care", "carp", "cart", "case", "cash",
  "cast", "cat", "cave", "cell", "cent", "chain", "chair", "chalk", "chance",
  "change", "charge", "chart", "chase", "chat", "check", "cheese", "cherry", "chest",
  "chew", "chick", "child", "chip", "chocolate", "choice", "choir", "church", "circle",
  "claim", "clap", "class", "claw", "clay", "clean", "clear", "climb", "clip",
  "clock", "close", "cloth", "cloud", "club", "clue", "cluster", "coach", "coal",
  "coat", "code", "coffee", "coil", "coin", "cold", "collar", "collect", "color",
  "column", "comb", "come", "comfort", "command", "comment", "common", "company",
  "compare", "compass", "complete", "complex", "component", "compose", "compound", "comprehend",
  "compress", "compromise", "compute", "concentrate", "concept", "concern", "concert", "conclude",
  "condition", "conduct", "confess", "confide", "configure", "confirm", "conflict", "conform",
  "confront", "confuse", "congratulate", "connect", "conquer", "conscience", "conscious", "consent",
  "consequence", "consider", "consist", "console", "conspire", "constant", "construct", "consult",
  "consume", "contact", "contain", "contaminate", "contemplate", "contest", "context", "continue",
  "contract", "contradict", "contrast", "contribute", "control", "converse", "convert", "convict",
  "convince", "cook", "cool", "cooperate", "coordinate", "cope", "copy", "core", "corner",
  "correct", "correlate", "correspond", "corrupt", "cost", "cotton", "c ouch", "cough", "count",
  "country", "couple", "course", "court", "cousin", "cover", "cow", "crack", "craft",
  "crane", "crash", "crawl", "crazy", "cream", "create", "credit", "creep", "crew",
  "crime", "crimson", "critic", "criticize", "crop", "cross", "crow", "crowd", "crown",
  "crush", "cry", "crypt", "cube", "cubic", "cue", "cuff", "cuisine", "cultivate",
  "culture", "cup", "cupboard", "curb", "cure", "curl", "curly", "current", "curse",
  "curve", "cushion", "custom", "cut", "cycle", "cylinder", "dagger", "daily", "dairy",
  "dance", "danger", "dare", "dark", "dart", "dash", "data", "date", "daughter",
  "dawn", "day", "deal", "dean", "dear", "death", "debate", "debt", "decay", "deceit",
  "decide", "deck", "declare", "decorate", "deduce", "deed", "deep", "deer", "defeat",
  "defect", "defend", "define", "defy", "degree", "delay", "delete", "delight", "deliver",
  "demand", "demolish", "denial", "denounce", "dent", "deny", "depart", "depend", "deposit",
  "depress", "depth", "derive", "descend", "describe", "desert", "design", "desire", "despair",
  "destroy", "detail", "detect", "deter", "develop", "device", "devise", "devote", "dew",
  "diagram", "dial", "diamond", "diaper", "dictate", "die", "diet", "differ", "difficult",
  "diffuse", "digest", "digital", "dilemma", "dine", "dinner", "dip", "direct", "directory",
  "dirt", "dirty", "disagree", "disappear", "disaster", "disc", "discard", "discern", "discharge",
  "discipline", "disclose", "discount", "discourage", "discuss", "disease", "dish", "dismiss",
  "disorder", "display", "displease", "dispose", "dispute", "dissolve", "distance", "distinct",
  "distribute", "district", "distrust", "diverge", "diversity", "divide", "divine", "divorce",
  "dizzy", "dock", "doctor", "document", "dog", "dollar", "dome", "domestic", "donate",
  "door", "dose", "dot", "double", "dough", "dove", "down", "dozen", "draft", "drag",
  "dragon", "draw", "dream", "dress", "drift", "drill", "drink", "drive", "drop",
  "drought", "drown", "drum", "dry", "duck", "dull", "dumb", "dump", "dune", "dusk",
  "dust", "duty", "dwarf", "dwell", "dwindle", "dye", "dying", "each", "eagle", "ear",
  "earth", "ease", "east", "easy", "eat", "echo", "ecstasy", "edge", "edit", "educate",
  "effect", "effort", "egg", "ego", "eight", "either", "elbow", "elect", "element",
  "elevate", "elf", "elicit", "eliminate", "elite", "else", "embark", "embody", "emerge",
  "emotion", "empathy", "empire", "employ", "empty", "enable", "encourage", "end", "endure",
  "energy", "enforce", "engage", "engine", "enhance", "enjoy", "enlarge", "enlighten", "enlist",
  "enough", "enquire", "ensure", "enter", "entertain", "entire", "entity", "entrance", "entry",
  "envelope", "envy", "episode", "equal", "equation", "equip", "era", "erect", "erode",
  "err", "error", "escape", "essay", "establish", "estate", "estimate", "eternal", "ethic",
  "euphoria", "evade", "evaluate", "even", "event", "ever", "every", "evidence", "evil",
  "evolve", "exact", "exaggerate", "examine", "example", "excess", "exchange", "excite", "exclaim",
  "exclude", "excuse", "execute", "exempt", "exercise", "exhaust", "exhibit", "exile", "exist",
  "exit", "exodus", "expand", "expect", "expel", "expense", "experience", "experiment", "expert",
  "expire", "explain", "explode", "exploit", "explore", "export", "expose", "express", "extend",
  "extinct", "extreme", "eye", "eyebrow", "face", "fact", "factor", "factory", "faculty",
  "fade", "fail", "faint", "fair", "faith", "fall", "false", "fame", "family", "famous",
  "fan", "fancy", "fantasy", "far", "fare", "farm", "fashion", "fast", "fat", "fate",
  "father", "fault", "favor", "fear", "feast", "feather", "feature", "federal", "fee",
  "feed", "feel", "feet", "fell", "fellow", "felt", "female", "fence", "ferry", "fertile",
  "festival", "fetch", "fever", "few", "fiber", "fiction", "field", "fierce", "fifteen",
  "fifth", "fifty", "fight", "figure", "file", "fill", "film", "filter", "final",
  "finance", "find", "fine", "finger", "finish", "fire", "firm", "first", "fish",
  "fist", "fit", "five", "fix", "flag", "flame", "flash", "flat", "flavor", "flea",
  "flesh", "flex", "flick", "flight", "flip", "float", "flock", "floor", "flour", "flow",
  "flower", "flute", "fly", "foam", "focus", "fog", "fold", "folk", "follow", "food",
  "fool", "foot", "football", "for", "force", "forecast", "forehead", "forest", "forever",
  "forgive", "fork", "form", "formal", "format", "former", "formula", "forth", "fortress",
  "fortune", "forward", "fossil", "foster", "found", "foundation", "four", "fox", "fraction",
  "fragile", "frame", "frank", "fraud", "free", "freedom", "freeze", "french", "frequent",
  "fresh", "friction", "friend", "fright", "fringe", "frog", "from", "front", "frost",
  "frown", "fruit", "fuel", "full", "fun", "function", "fund", "funeral", "fungus", "fur",
  "furnace", "furniture", "fury", "fuse", "fusion", "future", "gadget", "gain", "galaxy",
  "gale", "gall", "game", "gang", "gap", "garage", "garden", "garlic", "gas", "gate",
  "gather", "gauge", "gaze", "gear", "gem", "general", "generate", "genius", "genre",
  "gentle", "genuine", "geography", "geometry", "germ", "gesture", "get", "ghost", "giant",
  "gift", "giggle", "girl", "give", "glad", "glance", "glare", "glass", "glide", "glitter",
  "globe", "glory", "glove", "glow", "goal", "goat", "god", "gold", "golf", "good",
  "goose", "gorge", "gospel", "gossip", "govern", "government", "gown", "grab", "grace",
  "grade", "gradual", "graduate", "grain", "grand", "grant"];





  export let med = [
  "adventure", "beautiful", "courage", "diamond", "elephant", "fountain",
  "garden", "helicopter", "island", "jungle", "kitchen", "laptop", "magnet",
  "notebook", "octopus", "pyramid", "quarantine", "reindeer", "strawberry",
  "telephone", "umbrella", "vaccine", "wildlife", "xylophone", "yesterday",
  "zeppelin", "alligator", "butterfly", "champion", "delicious", "envelope",
  "friendship", "guitar", "horizon", "imagine", "jewelry", "kangaroo",
  "labyrinth", "mountain", "neighborhood", "orchestra", "piano", "quest",
  "river", "symphony", "telescope", "universe", "volcano", "wilderness",
  "yarn", "balloon", "crystal", "explore", "fantasy", "goldfish", "iceberg",
  "journey", "kite", "lemon", "parachute", "quilt", "rocket", "seashell",
  "treasure", "x-ray", "yellow", "airplane", "ballerina", "cloud", "dragon",
  "engine", "flower", "glacier", "honeycomb", "invisible", "jigsaw", "keyhole",
  "neon", "octagon", "parrot", "questionnaire", "rhythm", "submarine", "trophy",
  "unicorn", "violin", "whirlpool", "yodel", "zeal", "accordion", "bonfire",
  "clock", "dolphin", "earthquake", "feather", "geology", "hamster", "icicle",
  "jukebox", "lighthouse", "meadow", "nucleus", "opossum", "polar", "quartz",
  "rainbow", "satellite", "trampoline", "uranium", "vegetarian", "wizard",
  "xenon", "yacht", "zephyr", "astronaut", "boomerang", "camera", "dinosaur",
  "firework", "galaxy", "hippopotamus", "inflatable", "jet", "kingdom", "llama",
  "nebula", "peacock", "quicksand", "robot", "saturn", "tornado", "waterfall",
  "xenophobia", "yeti", "zoo", "acorn", "butter", "coconut", "echo", "flame",
  "giant", "iguana", "jade", "kiwi", "ladybug", "mantis", "narwhal", "orbit",
  "pegasus", "quill", "ruby", "sphinx", "tiger", "unicycle", "volley", "windmill",
  "zodiac", "avalanche", "bamboo", "cactus", "dandelion", "eclipse", "falcon",
  "geyser", "harmonica", "incense", "jasmine", "kaleidoscope", "lantern",
  "monsoon", "neutron", "oasis", "penguin", "quicksilver", "radiance", "saffron",
  "tapestry", "utopia", "vortex", "walrus", "xanadu", "yukon", "zenith",
  "albatross", "bonsai", "chameleon", "daffodil", "evergreen", "firefly",
  "gazelle", "hummingbird", "iris", "jellyfish", "koala", "lavender", "mermaid",
  "nightingale", "orchid", "panda", "quokka", "rhinoceros", "starfish",
  "tulip", "urchin", "vulture", "wombat", "xerox", "yogurt", "zebra",
  "archipelago", "bioluminescence", "chrysalis", "dewdrop", "equinox",
  "fjord", "ginkgo", "halcyon", "iridescent", "juniper", "krypton", "luminous",
  "mirage", "nirvana", "obelisk", "phosphorescence", "quasar", "renaissance",
  "solstice", "tundra", "ultramarine", "vernal", "wisteria", "xanthic",
  "yttrium", "zircon", "aurora", "borealis ", "cathedral", "dynamite", "elegy",
  "flamenco", "gargoyle", "hieroglyph", "ichthyosaur", "jester", "kaleidoscope",
  "lullaby", "megalith", "naiad", "oceanic", "papillon", "quandary", "relic",
  "sorbet", "tessellation", "umbra", "vesper", "waltz", "xenon", "yonder",
  "zest", "abacus", "bouquet", "cascadia", "daisy", "ecstasy", "flora",
  "giggle", "honeybee", "ivory", "jubilee", "kettle", "lullaby", "mango",
  "nougat", "oceanview", "paprika", "quartzite", "raindrop", "sapphire",
  "tangerine", "unicorn", "violet", "wisteria", "xanthosis", "yogic", "zestful",
  "amethyst", "bougainvillea", "cantaloupe", "daffodil", "emerald", "flamingo",
  "giraffe", "hazelnut", "igloo", "jester", "kaleidoscope", "lapis", "mango",
  "nougat", "oceanic", "paprika", "quartz", "rainbow", "sapphire", "tangerine",
  "unicorn", "violet", "wisteria", "xanthosis", "yogic", "zestful", "amber",
  "bougainvillea", "cantaloupe", "daisy", "emerald", "flamingo", "giraffe",
  "hazelnut", "igloo", "jester", "kaleidoscope", "lapis", "mango", "nougat",
  "oceanic", "paprika", "quartz", "rainbow", "sapphire", "tangerine", "unicorn",
  "violet", "wisteria", "xanthosis", "yogic", "zestful", "apricot", "bougainvillea",
  "cantaloupe", "daisy", "emerald", "flamingo", "giraffe", "hazelnut", "igloo",
  "jester", "kaleidoscope", "lapis", "mango", "nougat", "oceanic", "paprika",
  "quartz", "rainbow", "sapphire", "tangerine", "unicorn", "violet", "wisteria",
  "xanthosis", "yogic", "zestful", "apricot", "bougainvillea", "cantaloupe",
  "daisy", "emerald", "flamingo", "giraffe", "hazelnut", "igloo", "jester",
  "kaleidoscope", "lapis", "mango", "nougat", "oceanic", "paprika", "quartz",
  "rainbow", "sapphire", "tangerine", "unicorn", "violet", "wisteria",
  "xanthosis", "yogic", "zestful", "apricot", "bougainvillea", "cantaloupe",
  "daisy", "emerald", "flamingo", "giraffe", "hazelnut", "igloo", "jester",
  "kaleidoscope", "lapis", "mango", "nougat", "oceanic", "paprika", "quartz",
  "rainbow", "sapphire", "tangerine", "unicorn", "violet", "wisteria",
  "xanthosis", "yogic", "zestful"
];

export let hard = [
  "abnormal appearance", "hostile attitude", "engaging discussion", "unlike others", "short-lived phenomenon", "greatly surprised",
  "highly sociable", "creative thinking", "unique person", "relative assessment", "changing patterns",
  "very chatty", "complete change", "intentionally cruel", "sound imitation", "great kindness",
  "absolutely necessary", "fun-loving nature", "joyful feeling", "constant worry", "all around",
  "highly irritating", "original thinking", "intense dread", "constant motion", "gentle wind", "wrong interpretation",
  "forcefully separate", "complex problem", "not included", "gradually deteriorate", "without worry", "city growth",
  "well organized", "firmly resistant", "completely different", "brightly hued", "creating words",
  "deeply compassionate", "overcast sky", "greatly perplex", "ideal example", "eager learner",
  "nocturnal walker", "triskaidekaphobia exists", "not straightforward", "wanderlust feeling", "unfairly biased",
  "big data", "beer making", "extremely angry", "showing contempt", "easily surrender", "clearly visible",
  "generously giving", "mental disarray", "highly intricate", "gross overstatement", "deeply embarrassing", "stark difference",
  "exacted price", "deeply sorrowful", "dishonest speaking", "recently coined", "logical inconsistency", "redacted information", "optimistically unrealistic",
  "extended speech", "violently windy", "physical attendance", "personal decision", "dangerously careless", "welcoming hospitality",
  "charmingly rural", "zeitgeist captured", "make relatable", "opposing views", "claustrophobia inducing", "deep melancholy",
  "stand-in replacement", "polysyllabic term", "widely varied", "stubbornly determined", "illusion-creating device", "lawsuit-prone",
  "authority craving", "excessively loud", "highly intelligent", "barely audible", "additional amount", "unethical behavior", "secretly concealed", "high regard",
  "wanderlust feeling", "frequently grumble", "highly excited", "protective cover", "openly unfriendly", "close bond",
  "verbal insult", "energetically animated", "money related", "outgoing personality", "serenely calm", "rule breaker", "deceptive act",
  "openly weeping", "constantly shifting", "highly damaging", "difficult manage", "easily frightened", "difficult situation", "intensely luminous",
  "excessive praiser", "shifting allegiance", "difficult understand", "drastic alteration", "irresistibly attractive", "unusual formation", "loud cry", "highest point", "personal sacrifice",
  "guiding figure", "actively assist", "pessimistic outlook", "unpredictable nature", "extremely precise", "ostentatiously displayed",
  "excessive vanity", "judicial structure", "predetermined fate", "briefly stated", "slowly expiring", "barely noticeable",
  "peacefully tranquil", "deeply knowledgeable", "xenophile tendency", "moving air", "obviously true", "noticeably happy",
  "join together", "briefly existing", "diverse blend", "strongly encourage", "excessive pride",
  "dishonest behavior", "completely ruin", "overzealous believer", "incantation uttered", "calculating device", "extremely noisy", "exact replica",
  "religious study", "gradually disappearing", "body language", "hypochondria suffering",
  "quickly flee", "combat ready", "mentally process", "effervescently happy", "steadily increase", "extremely talkative", "overly theatrical", "financially ruined",
  "disposable item", "noisy disturbance", "itemized inventory", "horrifyingly graphic",
  "subtly mocking", "curative treatment", "difficult choice", "clever retort", "schadenfreude experience", "theatrical performer",
  "seemingly plausible", "exceptionally talented", "xenoglossic ability", "rapidly moving", "clock device",
  "openly hostile", "fully conscious", "potentially dangerous", "producing results", "overly abundant",
  "entirely unstoppable", "potential danger", "easily understood", " sickness suffering", "steadily growing", "partially shaded", "completely pure", "brightly sparkling",
  "completely equal", "take complete control", "thoughtfully considerate", "xenophobia feeling", "far-off distance",
  "eagerly enthusiastic", "excessive flattery", "emotional release", "moving slowly", "shining brightly", "socially adept",
  "funeral toll", "threshold level", "completely ordinary", "hardened exterior", "additional weight", "mutual compromise", "angelic nature",
  "greasy texture", "unusual behavior", "xenophile tendency", "strong desire", "educational process", "fortunate event",
  "acknowledge existence", "become acquainted", "great achievement", "exciting adventure", "alligator creature",
  "altruistic nature", "diplomatic representative", "ambiguous meaning", "amplifying device", "data analysis",
  "anticipate event", "software application", "building architect", "arrangement plan", "performance assessment",
  "assignment task", "social association", "background atmosphere", "breakthrough discovery",
  "breathtaking view", "broadcast transmission", "mathematical calculation", "joyful celebration", "difficult challenges",
  "championship title", "classification system", "collaborative effort", "comfortable feeling", "regulatory compliance",
  "complicated issue", "concentrate effort", "conclusion reached", "conference meeting",
  "connection established", "considerable amount", "construction process", "continuation phase", "contribution made",
  "coordinating effort", "corrective action", "creative thinking", "dedicated effort", "demonstration event",
  "development phase", "distinct difference", "disciplinary action", "discovery made", "documentary film",
  "economical solution", "electric power", "embarrassing situation", "enthusiastic feeling",
  "establishment founded", "evaluation process", "exaggerated statement", "explanation provided", "fantastic experience",
  "foundation laid", "friendship bond", "functional ability", "generational change", "government agency",
  "grateful feeling", "headquarters location", "identification process", "implementation phase",
  "improvement made", "independent entity", "information provided", "innovative idea", "installation process",
  "intelligent system", "interactive process", "interference issue", "investigation conducted", "journalistic reporting",
  "leadership role", "legislative act", "literary work", "management system", "manipulative behavior",
  "measurement tool", "meditative state", "modification made", "negotiation process", "observational study",
  "organizational structure", "partnership formed", "personality trait", "preparation phase", "presentation made",
  "procrastination habit", "productive output", "professional service", "programming language", "recognition received",
  "refrigeration system", "registration process", "relationship formed", "representative figure", "requirement met",
  "resolution passed", "responsibility taken", "satisfaction felt", "sensitive issue", "significant impact",
  "simplification process", "specification document", "spontaneous reaction", "substantial amount", "superintending role",
  "supervisory control", "synchronization process", "temperature reading", "termination point", "theoretical concept",
  "tournament competition", "transportation system", "understanding gained", "universal principle",
  "unpredictable outcome", "validation process", "verification step", "vocabulary list", "volunteering effort"
];



export let pro = [
  'Despite the rain, they continued their journey',
  'The professor finally paused for questions',
  'The results were promising, but more tests were needed',
  'The team celebrated finishing ahead of schedule',
  'Her quick thinking prevented a worse outcome',
  'The delayed meeting was set for next week',
  'While waiting for the train, they discussed plans',
  'Though tired, he agreed to stay longer',
  'Once the decision was made, there was no turning back',
  'If we don’t act now, we may miss the chance',
  'Had I known, I would have spoken sooner',
  'The renowned artist refused to compromise on quality',
  'When midnight struck, celebrations began',
  'If the weather holds, the event will go ahead',
  'Though they disagreed, they stayed friends',
  'The long report was completed quickly',
  'Even with a head start, he lost the race',
  'As soon as they left, the storm began',
  'Given the circumstances, their performance was great',
  'After sunset, the temperature dropped fast',
  'Had she waited, she would have caught the train',
  'By the time they arrived, the show started',
  'The issue was too complex for a quick solution',
  'He ran, but missed the bus by seconds',
  'Had I known, I would have attended the meeting',
  'When the alarm sounded, everyone evacuated',
  'The well-rehearsed presentation faced technical issues',
  'Once signed, the deal was done',
  'With new evidence, the case reopened',
  'Feel free to ask any questions',
  'She finished the race despite leg pain',
  'The CEO announced his retirement',
  'Without a miracle, we’ll miss the deadline',
  'Given the effort, the result was impressive',
  'When in the city, they visited a coffee shop',
  'She couldn’t open the door, despite her efforts',
  'Despite risks, they invested in the venture',
  'Leave now to avoid traffic',
  'Though hesitant, he agreed eventually',
  'Though the odds were bad, they tried',
  'After the meeting, they went to dinner',
  'Early warning prevented greater damage',
  'The long-awaited proposal was submitted',
  'After finishing, they took a break',
  'Despite strong evidence, he claimed innocence',
  'If funding is approved, construction begins next month',
  'Quick response prevented further fire spread',
  'Despite the tight budget, the project was done on time',
  'After hearing the news, they prepared',
  'Their plan failed despite best efforts',
  'Had she known, she would’ve bought it sooner',
  'The surprise decision was long-awaited',
  'After the policy change, satisfaction improved',
  'Given the economy, they paused expansion plans',
  'Hard work leads to success',
  'Though the situation looked bad, they stayed hopeful',
  'The initially doubted project succeeded',
  'Though the weather was bad, the event succeeded',
  'If conditions hold, the launch will go ahead',
  'Had she studied harder, she’d have passed easily',
  'The product was finally ready for market',
  'They finished the complex task early',
  'In the city, he visits his favorite bookstore',
  'Though risky, they proceeded with the plan',
  'After the results, they celebrated',
  'Given the effort, the team did great',
  'Had you told me earlier, I could’ve helped',
  'Though tired, the team stayed motivated',
  'Quick response saved the day',
  'Though costly, they deemed it worth it',
  'The anticipated announcement shocked many',
  'Though difficult, they reached safely',
  'At sunrise, they began the hike',
  'They pushed through challenges to finish',
  'Once repairs finished, the building reopened',
  'Had I known, I would have applied',
  'After months of work, the team relaxed',
  'Though weather was unpredictable, the event happened',
  'She always visited old friends when home',
  'It was late, so they postponed the meeting',
  'With no experience, he did well',
  'Early setbacks didn’t stop success',
  'Once signed, work began immediately',
  'Their preparation changed the outcome',
  'The long-standing policy was updated',
  'Leaving earlier would’ve avoided traffic',
  'After the deadline, no submissions were accepted',
  'Despite delays, the project succeeded',
  'Follow the instructions for an easier task',
  'The decision was controversial but right',
  'On free weekends, they went camping',
  'Given the time, the work was impressive',
  'Though tired, they worked until it was done'
];
