const words = [
    "banana", "conquer", "architecture", "xenophobia", "interview", "fortunate", "education", 
    "ability", "mistake", "yesterday", "airport", "balloon", "incredible", "universe", "happiness",
    "destruction", "elephant", "library", "available", "chocolate", "giraffe", "fireworks", 
    "hydration", "jacket", "keyboard", "landscape", "mountain", "Neighborhood", "octopus", 
    "pollution", "quiz", "restaurant", "superior", "telephone", "umbrella", "vehicle", "wizard", 
    "xylophone", "Yellow", "zealous", "oxygen", "telescope", "achievement", "barbecue", "container", 
    "dangerous", "efficient", "friendship", "gigantic", "historical", "innovation", "justice", 
    "knowledge", "luxurious", "meditation", "negotiation", "orchestra", "perspective", 
    "quarantine", "resilient", "strategic", "technology", "understanding", "validation", 
    "wonderful", "expectation", "zoology", "adventure", "breakfast", "celebration", "determination", 
    "evolution", "fascination", "gratitude", "hurricane", "imagination", "jurisdiction", "kilometer", 
    "landlord", "motivation", "Navigation", "opportunity", "perception", "qualification", 
    "reliability", "statistics", "transformation", "unbelievable", "vibration", "workshop", 
    "xenon", "youthful", "zebra", "apple", "grape", "cupcake", "python", "database", "elevator", 
    "rainfall", "newspaper", "danger", "ocean", "flower", "computer", "notebook", "signal", 
    "energy", "puzzle", "planet", "radio", "quicksand", "money", "lamp", "catastrophe", "guitar", 
    "burger", "internet", "swimming", "zodiac", "television", "quizlet", "envelope", "feather", 
    "galaxy", "hammer", "important", "jellyfish", "kangaroo", "leaflet", "monument", "network", 
    "outstanding", "penguin", "Quotation", "rainbow", "snowflake", "traveller", "umbrella", 
    "village", "whisper", "xerox", "yogurt", "zookeeper", "basketball", "direction", "enthusiasm", 
    "frustration", "glacier", "highlight", "impressive", "judgment", "knowledgeable", "lightning", 
    "management", "neutral", "optimism", "persistence", "realization", "surprising", "thrilling", 
    "unique", "vacation", "wilderness", "xylophone", "yawning", "zucchini", "entertainment", 
    "football", "generation", "hospitality", "inspiration", "journey", "kingdom", "landslide", 
    "momentum", "networking", "operation", "priority", "recognition", "supportive", "tradition", 
    "utensil", "volcano", "windshield", "yelling", "zone", "algorithm", "backyard", "chemistry", 
    "development", "election", "foundation", "geography", "hesitation", "illusion", "jealousy", 
    "knitting", "leadership","apple", "book", "cat", "dog", "elephant", "fish", "grape", "hat", "ice", "joke",
    "kite", "lamp", "moon", "nest", "orange", "pear", "queen", "river", "sun", "tree",
    "umbrella", "vase", "wolf", "xylophone", "yarn", "zebra", "broom", "cloud", "dew",
    "egg", "fan", "glove", "horse", "iron", "jelly", "key", "lion", "map", "nut", "owl",
    "plum", "quiz", "rose", "star", "tiger", "urn", "violin", "wax", "yak", "zip", "ball",
    "chair", "door", "ear", "frog", "guitar", "hammer", "igloo", "jug", "kangaroo", "leaf",
    "mountain", "noon", "oak", "pan", "quilt", "ring", "swan", "toe", "unicorn", "vulture","accomplish", "adventure", "ambitious", "beautifully", "challenging", "delightful",
    "education", "fortunate", "generosity", "acknowledge", "acquainted", "achievement", "adventure", "alligator", 
    "altruistic", "ambassador", "ambiguous", "amplifier", "analytics", 
    "anticipate", "application", "architect", "arrangement", "assessment",
    "assignment", "association", "atmosphere", "background", "breakthrough", 
    "breathtaking", "broadcasting", "calculation", "celebration", "challenges", 
    "championship", "classification", "collaboration", "comfortable", "comparison", 
    "compliance", "complicated", "concentrate", "conclusion", "conference", 
    "connection", "considerable", "construction", "continuation", "contribution", 
    "coordination", "correction", "creativity", "dedication", "demonstration", 
    "development", "difference", "discipline", "discovery", "documentary", 
    "economical", "education", "electricity", "embarrassment", "enthusiasm", 
    "establishment", "evaluation", "exaggeration", "explanation", "fantastic", 
    "foundation", "friendship", "functionality", "generation", "government", 
    "gratitude", "headquarters", "identification", "imagination", "implementation", 
    "improvement", "independent", "information", "innovation", "installation", 
    "intelligence", "interaction", "interference", "investigation", "journalism", 
    "leadership", "legislation", "literature", "management", "manipulation", 
    "measurement", "meditation", "modification", "negotiation", "observation", 
    "organization", "partnership", "personality", "preparation", "presentation", 
    "procrastination", "productivity", "professional", "programming", "recognition", 
    "refrigeration", "registration", "relationship", "representation", "requirement", 
    "resolution", "responsibility", "satisfaction", "sensitivity", "significant", 
    "simplification", "specification", "spontaneous", "substantial", "superintendent", 
    "supervision", "synchronization", "temperature", "termination", "theoretical", 
    "tournament", "transformation", "transportation", "understanding", "universal", 
    "unpredictable", "validation", "verification", "vocabulary", "volunteering", 
    "abandon", "accept", "admire", "alert", "amuse", "apologize", "apply", 
    "approve", "arrange", "attend", "avoid", "believe", "blame", "borrow", 
    "bounce", "brush", "bury", "carry", "cheer", "clap", "compete", "confuse", 
    "copy", "crawl", "decide", "delay", "deliver", "deny", "destroy", "develop", 
    "divide", "doubt", "drag", "drip", "employ", "encourage", "enjoy", "expand", 
    "explain", "fancy", "follow", "gather", "grab", "hang", "hurry", "identify", 
    "imagine", "improve", "inform", "invite", "join", "jump", "knock", "launch", 
    "listen", "measure", "notice", "offer", "paint", "promise", "protect", 
    "provide", "push", "question", "recommend", "reflect", "remember", "remove", 
    "replace", "reply", "represent", "require", "rescue", "respect", "return", 
    "search", "smell", "spark", "suggest", "teach", "travel", "trust", "visit","happiness", "important", "journalist", 
    "knowledge", "landscape", "marvelous", "nostalgic", "opportunity", "perception", 
    "quantities", "reluctantly", "successful", "tolerance", "understand", "valuable", 
    "wonderful", "extraordinary", "yes", "zookeeper", "justification", "kidney", 
    "knighthood", "leadership", "mentor", "notorious", "opposite", "potential", "quirk", 
    "resume", "support", "timely", "understandable", "virtual", "wicked", "xylograph", 
    "yesterday", "zealot", "birthday", "courageous", "deer", "exciting", "fun", "generation", 
    "hill", "icicle", "jackal", "kite", "language", "manipulate", "navigation", "ocean", 
    "presentation", "resistance", "successful", "thoughtful", "unique", "versatile", 
    "wonderful", "yellow", "zephyr", "cupcake", "hairbrush", "sunglasses", "bookmark", 
    "pencil", "glue", "whiteboard", "eraser", "notebook", "calculator"
  ];
  
export default words;

